/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sem3;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;
/**
 *
 * @author oliver-dav
 */
public class InterfazGrafic extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafic
     */
    public InterfazGrafic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jButton1.setText("Dibujar linea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Dibujar Circulo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Dibujar cuadrado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Dibujar Rectangulo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Dibujar Pentagono");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Borrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Graphics panel = jPanel1.getGraphics();
        panel.setColor(Color.red);
        //panel.drawLine(110, 30, 20, 100);
        try{
            String punto1 = JOptionPane.showInputDialog(this,"Ingrese el punto 1");
            String punto2 = JOptionPane.showInputDialog(this,"Ingrese el punto 2");

            String[] p1 = punto1.split(",");
            String[] p2 = punto2.split(",");

            int x1 = Integer.parseInt(p1[0]);
            int y1 = Integer.parseInt(p1[1]);

            int x2 = Integer.parseInt(p2[0]);
            int y2 = Integer.parseInt(p2[1]);

            panel.drawLine(x1, y1, x2, y2);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese la informacion correcta");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Graphics panel = jPanel1.getGraphics();
        try{
            String punto1 = JOptionPane.showInputDialog(this,"Ingrese el punto central");
            String punto2 = JOptionPane.showInputDialog(this,"Ingrese el radio");

            String[] p1 = punto1.split(",");

            int x1 = Integer.parseInt(p1[0]);
            int y1 = Integer.parseInt(p1[1]);
            
            int radio = Integer.parseInt(punto2);
            
            panel.setColor(Color.BLUE);
            panel.drawOval(x1, y1, radio, radio);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(this, "Ingrese la informacion correcta"); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Graphics panel = jPanel1.getGraphics();
        try{
            String punto1 = JOptionPane.showInputDialog(this,"Ingrese el punto central");
            String punto2 = JOptionPane.showInputDialog(this,"Ingrese el tamanio");
            
            String[] p1 = punto1.split(",");
            int x1 = Integer.parseInt(p1[0]);
            int y1 = Integer.parseInt(p1[1]);
            
            int tama = Integer.parseInt(punto2);
            
            panel.setColor(Color.GREEN);
            panel.drawRect(x1, y1, tama, tama);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese la informacion correcta"); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Graphics panel = jPanel1.getGraphics();
        
        try{
            String punto1 = JOptionPane.showInputDialog(this,"Ingrese el punto central");
            String ancho = JOptionPane.showInputDialog(this,"Ingrese el ancho");
            String alto = JOptionPane.showInputDialog(this,"Ingrese el alto");
            
            String[] p1 = punto1.split(",");
            
            int x1 = Integer.parseInt(p1[0]);
            int y1 = Integer.parseInt(p1[1]);
            
            int width = Integer.parseInt(ancho);
            int height = Integer.parseInt(alto);
            
            panel.setColor(Color.black);
            panel.drawRect(x1, y1, width, height);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese la informacion correcta"); 
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Graphics panel = jPanel1.getGraphics();
        double anguloInicial = 52.5;
        
        try{
            String punto1 = JOptionPane.showInputDialog(this,"Ingrese el punto central");
            String radio = JOptionPane.showInputDialog(this,"Ingrese el radio");
            String[]p1 = punto1.split(",");
            
            int x2 = Integer.parseInt(p1[0]);
            int y2 = Integer.parseInt(p1[1]);
            double rad = Double.parseDouble(radio);
            int [] puntosX = new int [5];
            int [] puntosY = new int [5];
            
            for(int i = 0; i < 5; i++){
                double angulo = anguloInicial + ( 2 * Math.PI * i)/5;
                double x = x2 + rad * Math.cos(angulo);
                double y = y2 + rad * Math.sin(angulo);
                puntosX[i] = (int) x;
                puntosY[i] = (int) y;
            }
            
            panel.setColor(Color.black);
            panel.drawPolygon(puntosX, puntosY, 5);
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese la informacion correcta"); 
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel1.removeAll();
        jPanel1.updateUI();
    }//GEN-LAST:event_jButton6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
